### ISSUE TITLE
Missing build dependencies

### ISSUE THREAD

**Issue by hosiet** [linuxdeepin/dtksettings#1]
Missing build dependencies made it impossible to build a deb package from current source.

* qt5-qmake
* qtbase5-dev

P.S.: A spelling error in `debian/control`: powerfull -> powerful.

**Comment by Iceyer** [comment]
We add qt5-default, qt5-qmake and correct the spelling error here:
https://cr.deepin.io/#/c/22446/

**Comment by hosiet** [comment]
OK
